### ISSUE TITLE
在生成features.bin时出现 IndexError: index 1761 is out of bounds for axis 1 with size 1708  错误

### ISSUE THREAD

**Issue by licy3d** [openxrlab/xrlocalization#19]
首先感谢您的工作，为我提供了学习的机会！

0.我使用您提供的[数据集](https://openxrlab-share-mainland.oss-cn-hangzhou.aliyuncs.com/xrsfm/test_data.zip?versionId=CAEQQBiBgMCi_6mllxgiIGI2ZjM1YjE1NjBmNTRmYjc5NzZlMzZkNWY1ZTk1YWFj)生成 images.bin, points3D.bin，
1.按照  [step0](https://github.com/openxrlab/xrlocalization/blob/main/docs/en/tutorials/retriangulation.md)生成features.bin。
2.按照 [step0](https://github.com/openxrlab/xrlocalization/blob/main/docs/en/tutorials/generate_loc_map.md)生成新的模型时候出现 
`Traceback (most recent call last):
  File "tools/loc_convert_reconstruction.py", line 141, in <module>
    main(args.feature_path, args.model_path, args.output_path)
  File "tools/loc_convert_reconstruction.py", line 131, in main
    crm.convert_to_mean_descriptor_map(output_path)
  File "tools/loc_convert_reconstruction.py", line 116, in convert_to_mean_descriptor_map
    self.compute_mean_descriptor()
  File "tools/loc_convert_reconstruction.py", line 96, in compute_mean_descriptor
    descriptor = self.features[image_id].descriptors[:, point2d_id]
IndexError: index 1761 is out of bounds for axis 1 with size 1708` 
的错误。

不管我使用colmap 还是xrsfm生成模型，到步骤2时候都会报这个错误，我用界面colmap查看了模型，模型是没问题的。

多谢~

**Comment by HailinYu0414** [comment]
Hi~ 从报错来看, 是因为images.bin里面的特征点数量和features.bin里面的特征点数量不一致造成的, 在执行tools/loc_convert_reconstruction.py这个工具的时候有可能是稀疏重建和特征文件不一致, 确认一下你执行的步骤是否是按照下面这个顺序:
1. 先使用xrsfm 或 colmap获得一个基于SIFT特征的初始稀疏重建结果, 包括: cameras.bin, images.bin, 和 points3D.bin;
2. 根据上面的重建结果, 需要替换成localization中使用的feature做一次重新三角化, 参考[这里](https://github.com/openxrlab/xrlocalization/blob/main/docs/en/tutorials/retriangulation.md),   这一步执行完后, 会生成features.bin 和 新的 cameras.bin, images.bin, 和 points3D.bin;
3.  根据重新三角化的结果,  执行tools/loc_convert_reconstruction.py这个工具,  这个工具里使用的是第二步里面生成的稀疏模型(cameras.bin, images.bin, points3D.bi)和features.bin;

**Comment by licy3d** [comment]
> Hi~ 从报错来看, 是因为images.bin里面的特征点数量和features.bin里面的特征点数量不一致造成的, 在执行tools/loc_convert_reconstruction.py这个工具的时候有可能是稀疏重建和特征文件不一致, 确认一下你执行的步骤是否是按照下面这个顺序:
> 
>     1. 先使用xrsfm 或 colmap获得一个基于SIFT特征的初始稀疏重建结果, 包括: cameras.bin, images.bin, 和 points3D.bin;
> 
>     2. 根据上面的重建结果, 需要替换成localization中使用的feature做一次重新三角化, 参考[这里](https://github.com/openxrlab/xrlocalization/blob/main/docs/en/tutorials/retriangulation.md),   这一步执行完后, 会生成features.bin 和 新的 cameras.bin, images.bin, 和 points3D.bin;
> 
>     3. 根据重新三角化的结果,  执行tools/loc_convert_reconstruction.py这个工具,  这个工具里使用的是第二步里面生成的稀疏模型(cameras.bin, images.bin, points3D.bi)和features.bin;

多谢解惑，多谢您~
祝生活愉快~
